name: Test 1 Workflow

on:
  push:
    branches:
      - test_1   # Solo se ejecuta cuando subes cambios a test_1

jobs:
  imprimir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Impresión 1
        run: echo "Impresión 1"

      - name: Impresión 2
        run: echo "Impresión 2"

      - name: Impresión 3
        run: echo "Impresión 3"
